lingua/Models/ErrorViewModel.cs
namespace lingua.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lingua/Models/ViewModels/ProfileUserViewModel.cs
namespace lingua.Models.ViewModels
{
	public class ProfileUserViewModel
	{
		public byte EnglishLevel { get; set; }
		public int UserId { get; set; }
	}
}

lingua/Models/ViewModels/ProfileViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace lingua.Models.ViewModels
{
	public class ProfileViewModel
	{
		[Required]
		[Display(Name = "EnglishLevel")]
		public byte EnglishLevel { get; set; }

		[Required]
		[Display(Name = "UserId")]
		public int UserId { get; set; }
	}
}

lingua/Controllers/HomeController.cs
using lingua.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace lingua.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

lingua/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace lingua.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

lingua/Controllers/ProfileController.cs
using lingua.Models;
using lingua.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace lingua.Controllers
{
	public class ProfileController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Create()
		{
			return View();
		}
	}
}

lingua/Controllers/UserController.cs
using lingua.dal;
using lingua.Models;
using Microsoft.AspNetCore.Mvc;

namespace lingua.Controllers
{
	public class UserController : Controller
	{
		public IActionResult Index()
		{
			dalUser dbUser = new dalUser();
			var userList = dbUser.GetUserList();
			//ViewBag.userList = userList;
			return View(userList);

		}
	}
}

lingua/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["ButtonText"] = "Click me";
    ViewData["ButtonClass"] = "btn-primary";
    ViewData["OnClick"] = "HandleClick()";
}

<h2>Index</h2>

@Html.Partial("Components/_CustomButton")
<script>
    function HandleClick() {
        // Tu lógica aquí
        alert("Button clicked!");
    }
</script>

lingua/Views/Login/Index.cshtml
@{
	Layout = null;
	ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Login Example</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="~/css/login/style.css" asp-append-version="true" />
</head>

<body>
	<div class="form-wrapper">
		<main class="form-side">
			<a href="#" title="Logo">
				<img src="~/assets/laplace.svg" alt="Laplace Logo" class="logo">
			</a>
			<form class="my-form">
				<div class="form-welcome-row">
					<h1>Welcome back! &#128079;</h1>
					<h2>Login with your account!</h2>
				</div>
				<div class="socials-row">
					<a href="#" title="Use Apple">
						<img src="~/assets/apple.png" alt="Apple">
						Continue with Apple
					</a>
				</div>
				<div class="socials-row">
					<a href="#" title="Use Github">
						<img src="~/assets/google.png" alt="Google">
						Continue with Google
					</a>
				</div>
				<div class="divider">
					<div class="divider-line"></div>
					or
					<div class="divider-line"></div>
				</div>
				<div class="text-field">
					<label for="email">Email</label>
					<input type="email" id="email" name="email" autocomplete="off" placeholder="you@example.com"
						   required>
					<div class="error-message">Email in incorrect format</div>
				</div>
				<div class="text-field">
					<label for="password">Password</label>
					<input id="password" type="password" name="password" placeholder="Your password" title="Minimum 6 characters at
                                                        least 1 Alphabet and 1 Number"
						   pattern="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$" required>
					<div class="error-message">
						Minimum 6 characters at
						least 1 Alphabet and 1 Number
					</div>
				</div>
				<button class="my-form__button" type="submit">
					Sign In
				</button>
				<div class="my-form__actions">
					<div class="my-form__row">
						<span>Don't have an account?</span>
						<a href="#" title="Reset Password">
							Sign Up Now
						</a>
					</div>
				</div>
			</form>
		</main>
		<aside class="info-side">
			<div class="blockquote-wrapper">
				<img src="~/assets/returns.png" alt="Returns" class="returns">
				<blockquote>
					With Laplace, I have significantly outperformed S&P 500 in the last three
					years.
				</blockquote>
				<div class="author">
					<img src="~/assets/avatar.png" alt="Avatar" class="avatar">
					<span class="author-name">@@ai_trader</span>
				</div>
			</div>
		</aside>
	</div>
</body>

</html>

lingua/Views/Shared/Components/_CustomButton.cshtml
@{
    string buttonText = ViewData["ButtonText"] as string;
    string buttonClass = ViewData["ButtonClass"] as string;
    string onClick = ViewData["OnClick"] as string;
}

<button class="btn @buttonClass" onclick="@onClick">@buttonText</button>

lingua/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - lingua</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	@* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
	@* <link rel="stylesheet" href="~/lingua.styles.css" asp-append-version="true" /> *@
	<link rel="stylesheet" href="~/css/footer/v1.css" asp-append-version="true" />
	@RenderSection("Styles", required: false)
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lingua</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer>
		<div class="footer-wrapper">
			<div class="footer-columns">
				<section class="footer-logo-column">
					<a href="/" aria-label="Go to GitHub homepage" class="footer-logo">
						<svg height="30" aria-hidden="true" viewBox="0 0 45 16" version="1.1" width="84"
							 data-view-component="true">
							<path d="M8.81 7.35v5.74c0 .04-.01.11-.06.13 0 0-1.25.89-3.31.89-2.49 0-5.44-.78-5.44-5.92S2.58 1.99 5.1 2c2.18 0 3.06.49 3.2.58.04.05.06.09.06.14L7.94 4.5c0 .09-.09.2-.2.17-.36-.11-.9-.33-2.17-.33-1.47 0-3.05.42-3.05 3.73s1.5 3.7 2.58 3.7c.92 0 1.25-.11 1.25-.11v-2.3H4.88c-.11 0-.19-.08-.19-.17V7.35c0-.09.08-.17.19-.17h3.74c.11 0 .19.08.19.17Zm35.85 2.33c0 3.43-1.11 4.41-3.05 4.41-1.64 0-2.52-.83-2.52-.83s-.04.46-.09.52c-.03.06-.08.08-.14.08h-1.48c-.1 0-.19-.08-.19-.17l.02-11.11c0-.09.08-.17.17-.17h2.13c.09 0 .17.08.17.17v3.77s.82-.53 2.02-.53l-.01-.02c1.2 0 2.97.45 2.97 3.88ZM27.68 2.43c.09 0 .17.08.17.17v11.11c0 .09-.08.17-.17.17h-2.13c-.09 0-.17-.08-.17-.17l.02-4.75h-3.31v4.75c0 .09-.08.17-.17.17h-2.13c-.08 0-.17-.08-.17-.17V2.6c0-.09.08-.17.17-.17h2.13c.09 0 .17.08.17.17v4.09h3.31V2.6c0-.09.08-.17.17-.17Zm8.26 3.64c.11 0 .19.08.19.17l-.02 7.47c0 .09-.06.17-.17.17H34.6c-.07 0-.14-.04-.16-.09-.03-.06-.08-.45-.08-.45s-1.13.77-2.52.77c-1.69 0-2.92-.55-2.92-2.75V6.25c0-.09.08-.17.17-.17h2.14c.09 0 .17.08.17.17V11c0 .75.22 1.09.97 1.09s1.3-.39 1.3-.39V6.26c0-.11.06-.19.17-.19Zm-17.406 5.971h.005a.177.177 0 0 1 .141.179v1.5c0 .07-.03.14-.09.16-.1.05-.74.22-1.27.22-1.16 0-2.86-.25-2.86-2.69V8.13h-1.11c-.09 0-.17-.08-.17-.19V6.58c0-.08.05-.15.13-.17.07-.01 1.16-.28 1.16-.28V3.96c0-.08.05-.13.14-.13h2.16c.09 0 .14.05.14.13v2.11h1.59c.08 0 .16.08.16.17v1.7c0 .11-.07.19-.16.19h-1.59v3.131c0 .47.27.83 1.05.83.247 0 .481-.049.574-.05ZM12.24 6.06c.09 0 .17.08.17.17v7.37c0 .18-.05.27-.25.27h-1.92c-.17 0-.3-.07-.3-.27V6.26c0-.11.08-.2.17-.2Zm29.99 3.78c0-1.81-.73-2.05-1.5-1.97-.6.04-1.08.34-1.08.34v3.52s.49.34 1.22.36c1.03.03 1.36-.34 1.36-2.25ZM11.19 2.68c.75 0 1.36.61 1.36 1.38 0 .77-.61 1.38-1.36 1.38-.77 0-1.38-.61-1.38-1.38 0-.77.61-1.38 1.38-1.38Zm7.34 9.35v.001l.01.01h-.001l-.005-.001v.001c-.009-.001-.015-.011-.024-.011Z">
							</path>
						</svg>
					</a>
					<div>
						<h3>Subscribe to our developer newsletter</h3>
						<p>Get tips, technical guides, and best practices. Once a month. Right in your inbox.</p>
					</div>
					<a class="subscribe-btn" href="https://resources.github.com/newsletter/">
						Subscribe
					</a>
				</section>
				<div class="other-columns">
					<section>
						<h3>Product</h3>
						<ul>
							<li>
								<a href="#" title="Features">Features</a>
							</li>
							<li>
								<a href="#" title="Enterprise">Enterprise</a>
							</li>
							<li>
								<a href="#" title="Copilot">Copilot</a>
							</li>
							<li>
								<a href="#" title="Security">Security</a>
							</li>
							<li>
								<a href="#" title="Pricing">Pricing</a>
							</li>
							<li>
								<a href="#" title="Team">Team</a>
							</li>
							<li>
								<a href="#" title="Resources">Resources</a>
							</li>
							<li>
								<a href="#" title="Roadmap">Roadmap</a>
							</li>
						</ul>
					</section>
					<section>
						<h3>Resources</h3>
						<ul>
							<li>
								<a href="#" title="Support">Support</a>
							</li>
							<li>
								<a href="#" title="Sitemap">Sitemap</a>
							</li>
							<li>
								<a href="#" title="Newsletter">Newsletter</a>
							</li>
							<li>
								<a href="#" title="Help Centre">Help Centre</a>
							</li>
							<li>
								<a href="#" title="Investor">Investor</a>
							</li>
						</ul>
					</section>
					<section>
						<h3>Support</h3>
						<ul>
							<li>
								<a href="#" title="About Us">Docs</a>
							</li>
							<li>
								<a href="#" title="Blog">Community Forum</a>
							</li>
							<li>
								<a href="#" title="Careers">Professional Services</a>
							</li>
							<li>
								<a href="#" title="Press">Premium Support</a>
							</li>
							<li>
								<a href="#" title="Contact">Skills</a>
							</li>
							<li>
								<a href="#" title="Contact">Status</a>
							</li>
							<li>
								<a href="#" title="Contact Github">Contact Github</a>
							</li>
						</ul>
					</section>
					<section>
						<h3>Company</h3>
						<ul>
							<li>
								<a href="#" title="Terms and services">
									About
								</a>
							</li>
							<li>
								<a href="#" title="Privacy Policy">
									Customer Stories
								</a>
							</li>
							<li>
								<a href="#" title="Cookies">
									Blog
								</a>
							</li>
							<li>
								<a href="#" title="Licenses">
									Licenses
								</a>
							</li>
							<li>
								<a href="#" title="Cookies">
									Contact
								</a>
							</li>
						</ul>
					</section>
				</div>
			</div>
		</div>
		<!-- bottom part section -->
		<div class="footer-bottom">
			<div class="footer-bottom-wrapper">
				<small>© <span id="year"></span> GitHub Inc.</small>
				<ul class="footer-bottom-links">
					<li>
						<a href="#" title="Terms">Terms</a>
					</li>
					<li>
						<a href="#" title="Privacy">Privacy</a>
					</li>
					<li>
						<a href="#" title="Security">Sitemap</a>
					</li>
					<li>
						<a href="#" title="Security">What is Git?</a>
					</li>
				</ul>
				<div class="social-wrapper">
					<div class='social-links'>
						<ul>
							<li>
								<a href="#" title="Facebook">
									<img src="~/assets/facebook.svg" alt='Facebook'>
								</a>
							</li>
							<li>
								<a href="#" title="Instagram">
									<img src="~/assets/instagram.svg" alt='Instagram'>
								</a></a>
							</li>
							<li>
								<a href="#" title="Linkedin">
									<img src="~/assets/linkedin.svg" alt='Linkedin'>
								</a>
							</li>
							<li>
								<a href="#" title="Twitter">
									<img src="~/assets/twitter.svg" alt='Twitter'>
								</a>
							</li>
							<li>
								<a href="#" title="Youtube">
									<img src="~/assets/youtube.svg" alt='YouTube'>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>

		</div>
	</footer>
	<script>
		document.getElementById("year").innerHTML = new Date().getFullYear();
	</script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

lingua/Views/User/Index.cshtml
@using lingua.be;

 @model List<beUser>

@{
	ViewBag.Title = "Users";
	// List<beUser> users = (List<beUser>)ViewBag.userList;
}


<h1>Users</h1>

<button type="button" onclick="window.location.href='@Url.Action("Create")'">Crear</button>


<table class="table">
	<thead>
		<tr>
			<th>
				Email
			</th>
		</tr>
	</thead>
	<tbody>

		@foreach (beUser user in Model)
		{
			<tr>
				<td>@user.Email</td>
			</tr>
		}
	</tbody>

</table>